name: fwfh_chewie
version: 0.7.0+1
description: WidgetFactory extension to render VIDEO with the chewie plugin.
homepage: https://github.com/daohoangson/flutter_widget_from_html
environment:
  sdk: ">=2.16.0 <3.0.0"
dependencies:
  chewie: ^1.3.4
  flutter:
    sdk: flutter
  flutter_widget_from_html_core:
    git:
      url: https://github.com/vtsindia-dev/flutter_widget_from_html_core.git
  video_player: ^2.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: any
  video_player_platform_interface: any
